# Generated by Django 5.1.6 on 2025-02-11 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.AlterField(
            model_name='question',
            name='passage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='exams.readingpassage'),
        ),
    ]
