# Generated by Django 5.1.6 on 2025-02-11 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_question_explanation_alter_question_passage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingpassage',
            options={'ordering': ['section']},
        ),
        migrations.AlterUniqueTogether(
            name='readingpassage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='readingpassage',
            name='order',
        ),
    ]
